### PR TITLE
re-add missing models/character.x

### PR DESCRIPTION
**Pull request by ritschwumm**
with minetest 0.4.16 this mod's characters are not displayed at all, obviously because `models/character.x` is missing. i don't know whether just re-adding it from the history is a good idea, but for me it fixes the problem.

### CODE REVIEW

**Comment by VanessaE** [comment]
The correct solution is not to re-add character.x but to change the mod to look for the correct minetest_game file.

**Comment by ritschwumm** [comment]
how can i find out which is is correct minetest_game file?
i'd be glad to open a new PR, but i don't even know where to look for it yet.

**Comment by VanessaE** [comment]
No need, I've just fixed the mod to use the correct file (627abc6bd8ce6cb54deda7111b02b16e28b9168b).  The model file is in <minetest_game>/mods/default/models.

**Comment by ritschwumm** [comment]
great, thank you very much :)

**Pull request closed without merging**
